"""empty message

Revision ID: 07346be699bb
Revises: e2c86ad35888
Create Date: 2021-04-28 23:25:22.167414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07346be699bb'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('mascot', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mascot')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'country')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
